### ISSUE TITLE
omxplayer sometimes doesn't exit 

### ISSUE THREAD

**Issue by najoshi** [KenT2/pipresents-next#29]
So I have had pipresents-next running (using mediashow) for a while in my digital photo frame, with some code modifications I have made for a motion sensor and buttons. Every so often the photo frame just dies and logging into the pi I notice that there are two omxplayers running. One is running a video from further back in the track list, and one is running a more recent video track. My assumption is that the monitor display somehow gets into a bad state because of the two omxplayers. Does this seem plausible and is there some way to make sure that omxplayer actually finishes?
- Nik.

**Comment by KenT2** [comment]
There have been a number of problems with omxplayer crashing and then not being deletable by PP. I thought I had caught them all but obviously not. This could well be one of those.

You could try a later version of omxplayer from here  http://omxplayer.sconde.net/

 Also it might be worth trying [pipresents-gapless] as in making it 'gapless' I rewrote a lot of the omxplayer interface code and I might have caught your problem.

You can kill left over omxplayers with killall omxplayer omxplayer.bin, the problem is where to put it in the code other than at the end.

**Comment by John37m** [comment]
Hello and thank you for writing the Pi Presents code. I work for the University of Florida Physics Dept and we have a small hands on science demonstrations museum in our lobby. I'm trying to use Pi Presents Next to create a slideshow that runs in a loop but when a guest presses a button to start the experiment running I'd like to interrupt the main slideshow and show a different (child or subshow) slideshow that explains what is happening. Once the second subshow  finishes when the experiment ends, I'd like to go back and continue with the main slideshow. I read in your change log that the beta version 1.3 has an "Enhanced - All shows now have their own controls instead of inheriting from their parent. This allows, for example, mediashows which are subshows of hyperlinkshows to have controls. controls.cfg is redundant and has been removed." To do what I want to accomplish with my shows do I need version 1.3 so that the main show runs until the visitor presses a button that would start the subshow, once the subshow ends it defaults back to the main show? Thank you. John Mocko

**Comment by KenT2** [comment]
Version 1.3 now has a relaible dbus implementation of the omxplayer interface.
