### ISSUE TITLE
Menu - Background music, and control settings

### ISSUE THREAD

**Issue by martinschultzkristensen** [KenT2/pipresents-next#54]
Hey.
Pipresents-next is great!

I run into two problems though:
But is it possible to play background music from a Menushow? -and to play sounds when changing between the different options?

I have a liveshow with a pp-childshow = a Menushow. I want user only can "enter" without pausing or exiting (In control section i set pp-stop null and pp-pause null).
But I want the user to be able to stop the mediashow (that is selected from the menushow).

I just cannot figure out how to do that, though I am searching the manual for answers. :)

Thanks for the help

**Comment by KenT2** [comment]
1. Playing music from a menushow
There is no simple way to do this. You can do it by having the music as a track in a separate mediashow and opening the show at the start of the menushow. If you want the music to stop when a menu option is selected you will need to close the music mediashow at the start of the selected track and open it again at the end. 
I would suggest you move to PP-Gapless, this has much better show control commands. Also in Gapless you may be able to use mute rather than stop (having sid this un-mute is broken in Stretch, it was OK in Jessie)

2. Play sounds when changing between menushow options.
Are you thinking of a beep when the cursor moves, if so its not possible. Could be a useful facility to have though bu tpossibly not easy to implemen as it needs a fast response time.

3. Stop in child show but not in its parent.
You definitely need to move to gapless. Next had a serious limitation that controls were inherited from the parent. In gapless each show has its own set of controls.

**Comment by martinschultzkristensen** [comment]
Hi,
Thanks for the answer.
I'll move to gapless and see what I can do.
